[package]
name = "application"
version = "0.1.0"
edition = "2018"


[dependencies]
domain = { path = "../domain" }

async-trait = { version = "0.1.51" }
log = { version = "0.4.14" }

[dev-dependencies]
tokio = { version = "1.0",  features = [ "full" ] }
mockall = { version = "0.10.2" }